#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

if [[ -n $3 ]]; then
    if [[ -z $4 ]]; then
	if [[ -d $1 ]]; then
	    scp -B -r "$1" "$3"@"$2":~/
	else
	    scp -B "$1" "$3"@"$2":~/
	fi
    else
	if [[ -d $1 ]]; then
	    scp -B -i "$4" -r "$1" "$3"@"$2":~/
        else
	    scp -B -i "$4" "$1" "$3"@"$2":~/
        fi
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
