#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

if [[ -n $3 ]]; then
    if [[ -z $4 ]]; then
	scp -B "$1" "$3"@"$2":~/
    else
	scp -B -i "$4" "$1" "$3"@"$2":~/
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
