#!/usr/bin/env bash
# Configure a Nginx server to redirect to another page
sudo sed -i "/server {/a location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 \n}; \n" /etc/nginx/sites-available/default

sudo nginx -s reload
