#!/usr/bin/env bash
# Configure a Nginx server to redirect to another page
sudo sed -i "/http {/a server {\nlocation /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n}\n} \n" /etc/nginx/nginx.conf

sudo nginx -s reload
