#!/usr/bin/env bash
# Configure a Nginx server to have a custom 404 page.

# update and install nginx
sudo apt update
sudo apt install nginx

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to redirect /redirect_me to another page
sudo sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /usr/share/nginx/html/error_404.html

sudo sed -i '/listen 80 default_server;/a \\n\terror_page 404 /error_404.html;\nlocation = /error_404.html {\n\t\troot /usr/share/nginx/html;\ninternal;\n}\n' /etc/nginx/sites-enabled/default

sudo service nginx restart
