#!/usr/bin/env bash
# manages manage_my_process.

command=$1

case $command in
    "start" )
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started" ;;
    "stop" )
        if test -f "/var/run/my_process.pid"; then
            kill "$(cat "/var/run/my_process.pid")"
        fi
        rm /var/run/my_process.pid
        echo "manage_my_process stopped";;
    "restart" )
        if test -f "/var/run/my_process.pid"; then
            kill "$(cat "/var/run/my_process.pid")"
        fi
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted" ;;
    * )
        echo "Usage: manage_my_process {start|stop|restart}" ;;
esac
