#!/usr/bin/env bash
# manages manage_my_process.

command=$1

case $command in
    "start" )
        ./manage_my_process &
        pgrep -f manage_my_process > /var/run/my_process.pid
        echo "manage_my_process started" ;;
    "stop" )
        kill "$(head -n 1 "/var/run/my_process.pid")"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped";;
    "restart" )
        kill "$(head -n 1 "/var/run/my_process.pid")"
        wait manage_my_process 2>/dev/null &
        rm /var/run/my_process.pid
        ./manage_my_process &
        pgrep -f manage_my_process > /var/run/my_process.pid
        echo "manage_my_process restarted" ;;
    * )
        echo "Usage: manage_my_process {start|stop|restart}" ;;
esac
